name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev \
                                  build-essential libssl-dev libffi-dev \
                                  python3-venv git libmtdev-dev xvfb \
                                  zlib1g-dev libglu1-mesa python3-distutils

      - name: Install Cython
        run: pip install Cython

      - name: Install Buildozer
        run: pip install --upgrade buildozer

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create license acceptance script
        run: |
          cat << EOF > accept_licenses.sh
          #!/bin/bash
          export ANDROID_HOME=\$HOME/.buildozer/android/platform/android-sdk
          export PATH=\$PATH:\$ANDROID_HOME/tools:\$ANDROID_HOME/platform-tools

          yes | \$ANDROID_HOME/tools/bin/sdkmanager --licenses
          yes | \$ANDROID_HOME/tools/bin/sdkmanager --update
          yes | \$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "ndk;25.2.9519653" "cmake;3.22.1"
          EOF
          chmod +x accept_licenses.sh

      - name: Update buildozer.spec
        run: |
          sed -i 's|^android.accept_sdk_license =.*|android.accept_sdk_license = True|' buildozer.spec
          sed -i 's|^p4a.branch =.*|p4a.branch = develop|' buildozer.spec
          echo "android.build_tools_version = 30.0.3" >> buildozer.spec

      - name: Build APK
        run: |
          ./accept_licenses.sh
          buildozer -v android debug

      - name: Check for APK files
        run: |
          if ls bin/*.apk 1> /dev/null 2>&1; then
            echo "APK files found."
          else
            echo "No APK files found."
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-files
          path: bin/*.apk
