name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev libmtdev-dev xvfb
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Install Android SDK components
        run: |
          yes | sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
      
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
      
      - name: Print Java version and JAVA_HOME
        run: |
          java -version
          echo $JAVA_HOME
      
      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-files
          path: ./bin/*.apk
