name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev libmtdev-dev xvfb  # Install PortAudio and MTDev libraries, along with Xvfb

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install required packages

      - name: List directory contents
        run: ls -al  # This helps verify your directory structure

      - name: Run Kivy application in Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &  # Start Xvfb
          export DISPLAY=:99  # Set display to Xvfb
          python main.py  # Run your main.py file

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-files
          path: ./bin/*.apk  # Ensure this path is correct, adjust if needed
