on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v3  # Update to the latest version
        with:
          python-version: '3.x'  # Specify the desired Python version
          workdir: './path/to/your/workdir'  # Use 'workdir' instead of 'work-dir'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
