name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev \
                                  build-essential libssl-dev libffi-dev \
                                  python3-venv git libmtdev-dev xvfb \
                                  zlib1g-dev libglu1-mesa python3-distutils

      - name: Install Cython
        run: pip install Cython

      - name: Set up Android SDK
        run: |
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip
          sudo mkdir -p /usr/local/android-sdk/cmdline-tools
          sudo mv cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/android-sdk/cmdline-tools/latest/bin:/usr/local/android-sdk/platform-tools" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: |
          yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=/usr/local/android-sdk

      - name: Install Android SDK components
        run: |
          /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

      - name: Install Buildozer
        run: pip install --upgrade buildozer

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Prepare Buildozer
        run: |
          buildozer init
          sed -i 's/^android.sdk_path =.*/android.sdk_path = \/usr\/local\/android-sdk/' buildozer.spec
          sed -i 's/^android.ndk_path =.*/android.ndk_path = \/usr\/local\/android-sdk\/ndk\/25.2.9519653/' buildozer.spec

      - name: Build APK
        run: buildozer -v android debug

      - name: Check for APK files
        run: |
          if ls bin/*.apk 1> /dev/null 2>&1; then
            echo "APK files found."
          else
            echo "No APK files found."
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-files
          path: bin/*.apk
