name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Build your project
        run: |
          cd ./path/to/your/workdir  # Change to your working directory
          # Your build commands here

      - name: List files in bin directory
        run: ls -al ./bin  # Debugging step

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-files
          path: ./bin/*.apk  # Ensure this path is correct
